### ISSUE TITLE
Drop all userland depenencies

### ISSUE THREAD

**Issue by hanneskod** [byrokrat/banking#17]
Libraries of this kind should not have user land dependencies in my opinion. Fix.

* [x] `byrokrat/id` is used to validate dates in personal id accounts.
* [x] `drupol/phpermutations` is used to iterate over rewriter permutations.

**Comment by drupol** [comment]
Hey,

Thanks for using phpermutations! Don't hesitate to report any issue with it.

**Comment by hanneskod** [comment]
done
